<?php
require_once __DIR__ . '/inc/auth.php'; login_gerekli(); finans_gerekli();
$id = (int)get('id'); $t = row("SELECT * FROM tedarikciler WHERE id=?", [$id]); if (!$t) redirect('tedarikciler.php');
$sid = (int)get('santiye_id'); $b = tedarikci_bakiye($id);
$w = $sid ? " AND g.santiye_id=?" : ''; $p = $sid ? [$id, $sid] : [$id];
$alim = rows("SELECT g.*, s.ad santiye, k.ad kat, k.ikon FROM giderler g JOIN santiyeler s ON s.id=g.santiye_id LEFT JOIN gider_kategorileri k ON k.id=g.kategori_id WHERE g.tedarikci_id=? $w ORDER BY g.tarih DESC LIMIT 200", $p);
$kira = rows("SELECT mk.*, s.ad santiye FROM makine_kiralama mk JOIN santiyeler s ON s.id=mk.santiye_id WHERE mk.tedarikci_id=? ORDER BY baslangic DESC", [$id]);
$odeme = rows("SELECT o.*, s.ad santiye, c.cek_no, c.vade, c.durum cdurum FROM tedarikci_odemeleri o LEFT JOIN santiyeler s ON s.id=o.santiye_id LEFT JOIN cekler c ON c.id=o.cek_id WHERE o.tedarikci_id=? ORDER BY o.tarih DESC LIMIT 200", [$id]);
$cekler = rows("SELECT * FROM cekler WHERE tedarikci_id=? AND yon='verilen' ORDER BY vade", [$id]);
$baslik = $t['firma']; $geri = 'tedarikciler.php'; include 'inc/layout_top.php'; ?>
<div class="kart" style="display:flex;justify-content:space-between;gap:.5rem;flex-wrap:wrap;align-items:center"><div><small><?= e($t['kategori']) ?> · VN: <?= e($t['vergi_no'] ?: '-') ?><br><svg class="ic" aria-hidden="true"><use href="#i-user-circle"></use></svg> <?= e($t['yetkili'] ?: '-') ?> · <svg class="ic" aria-hidden="true"><use href="#i-phone"></use></svg> <?= $t['telefon'] ? '<a href="tel:' . e($t['telefon']) . '">' . e($t['telefon']) . '</a>' : '-' ?></small></div>
<div style="display:flex;gap:.5rem"><a class="btn btn-cizgi btn-kucuk" href="tedarikci_form.php?id=<?= $id ?>"><svg class="ic" aria-hidden="true"><use href="#i-pencil-simple"></use></svg> Kart</a><a class="btn btn-yesil btn-kucuk" href="tedarikci_odeme_form.php?tedarikci_id=<?= $id ?>">+ Ödeme</a></div></div>
<div class="grid" style="grid-template-columns:repeat(3,1fr)"><div class="ozet ozet-mavi"><div class="baslik">Toplam alım</div><div class="rakam"><?= para($b['alim']) ?></div></div><div class="ozet ozet-yesil"><div class="baslik">Toplam ödeme</div><div class="rakam"><?= para($b['odeme']) ?></div></div><div class="ozet <?= $b['bakiye']>0?'ozet-kirmizi':'ozet-mavi' ?>"><div class="baslik">Borç bakiyesi</div><div class="rakam"><?= para($b['bakiye']) ?></div></div></div>
<h2>Alım geçmişi</h2>
<div class="araclar"><select onchange="location='?id=<?= $id ?>&santiye_id='+this.value"><option value="0">Tüm şantiyeler</option><?php foreach (santiyelerim() as $s): ?><option value="<?= $s['id'] ?>" <?= $s['id']==$sid?'selected':'' ?>><?= e($s['ad']) ?></option><?php endforeach; ?></select></div>
<div class="kart liste"><?php if (!$alim && !$kira): ?><div class="bos">Alım yok.</div><?php endif; foreach ($alim as $r): ?>
  <a class="satir" href="gider_form.php?id=<?= $r['id'] ?>"><div class="ico-b"><?= kat_ikon($r['ikon']) ?></div><div class="govde"><div class="ad"><?= e($r['aciklama'] ?: $r['kat']) ?></div><small><?= tarih_tr($r['tarih']) ?> · <?= e($r['santiye']) ?> <?= durum_etiketi($r['odeme_durumu']) ?></small></div><div class="tutar kirmizi"><?= para($r['tutar']) ?></div></a><?php endforeach; ?>
  <?php foreach ($kira as $r): ?><div class="satir"><div class="ico-b"><svg class="ic" aria-hidden="true"><use href="#i-tractor"></use></svg></div><div class="govde"><div class="ad">Kiralama: <?= e($r['makine_adi']) ?></div><small><?= tarih_tr($r['baslangic']) ?> → <?= tarih_tr($r['bitis']) ?> · <?= e($r['santiye']) ?></small></div><div class="tutar kirmizi"><?= para($r['toplam']) ?></div></div><?php endforeach; ?></div>
<h2>Ödeme geçmişi</h2>
<div class="kart liste"><?php if (!$odeme): ?><div class="bos">Ödeme yok.</div><?php endif; foreach ($odeme as $r): ?>
  <div class="satir"><div class="ico-b"><?= ['nakit'=>'<svg class="ic" aria-hidden="true"><use href="#i-money-wavy"></use></svg>','havale'=>'<svg class="ic" aria-hidden="true"><use href="#i-bank"></use></svg>','cek'=>'<svg class="ic" aria-hidden="true"><use href="#i-files"></use></svg>'][$r['tip']] ?></div><div class="govde"><div class="ad"><?= tip_adi($r['tip']) ?><?= $r['cek_no'] ? ' ' . e($r['cek_no']) : '' ?></div><small><?= tarih_tr($r['tarih']) ?> · <?= e($r['santiye'] ?: 'Genel') ?> <?= $r['vade'] ? '· vade ' . tarih_tr($r['vade']) . ' ' . durum_etiketi($r['cdurum']) : '' ?> <?= e($r['aciklama']) ?></small></div><div class="tutar yesil"><?= para($r['tutar']) ?></div><a class="btn btn-gri btn-kucuk" href="sil.php?t=tedarikci_odemeleri&id=<?= $r['id'] ?>&geri=tedarikci.php?id=<?= $id ?>" data-onay="Ödeme silinsin mi?"><svg class="ic" aria-hidden="true"><use href="#i-trash"></use></svg></a></div><?php endforeach; ?></div>
<?php if ($cekler): ?><h2>Verilen çekler</h2><div class="tablo-kutu"><table><tr><th>Çek no</th><th>Banka</th><th>Vade</th><th>Durum</th><th class="num">Tutar</th></tr><?php foreach ($cekler as $c): ?><tr><td><?= e($c['cek_no']) ?></td><td><?= e($c['banka']) ?></td><td><?= tarih_tr($c['vade']) ?></td><td><?= durum_etiketi($c['durum']) ?> <a class="btn btn-gri btn-kucuk" href="cek_durum.php?id=<?= $c['id'] ?>&geri=tedarikci.php?id=<?= $id ?>">değiştir</a></td><td class="num kirmizi"><?= para($c['tutar']) ?></td></tr><?php endforeach; ?></table></div><?php endif; ?>
<?php include 'inc/layout_bottom.php';
